# Setup Ollama - Colab

In [80]:
# %pip install colab-xterm
# %load_ext colabxterm

Lanch xtrem terminal in window.

%xterm

Download and run ollama server

curl -sSL https://ollama.ai/install.sh | sh && ollama serve

In [81]:
# !curl http://localhost:11434/api/pull -d '{  "model": "gemma3:12b" }'

In [82]:
# !curl http://localhost:11434/api/pull -d '{  "model": "nomic-embed-text" }'

# Setup tools

In [83]:
# %pip install -qU pandas langchain-ollama langchain-community langchain-text-splitters pypdf

In [84]:
import pandas as pd

from langchain.document_loaders import PyPDFLoader
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import OllamaLLM, OllamaEmbeddings
from langchain.prompts import PromptTemplate
from langchain.base_language import BaseLanguageModel
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

from pathlib import Path

In [ ]:
class CFG:
    model = "gemma3:12b"
    model_embed = "nomic-embed-text"
    rag_file = Path("ustawa_o_sygnalistach.pdf")
    questions_file = "train.csv"
    llm_models = [
        "qwen2.5:14b",
        "gemma3:12b",
        "SpeakLeash/bielik-11b-v2.3-instruct:Q4_K_M",
        "deepseek-r1:14b",
    ]


AI_PROMPT = """" 
Jesteś modelem AI, który odpowiada na pytania użytkownika wyłącznie w formie liczbowej.

Użytkownik poda dwa elementy:

Question: pytanie, na które należy odpowiedzieć.
Context: kontekst zawierający dane potrzebne do odpowiedzi.

---

Zasady:

Jeśli w Context znajduje się wartość liczbowa, zwracasz ją jako odpowiedź.
Jeśli Context zawiera przedział liczbowy (np. 10–20), zwracasz maksymalną wartość, chyba że Question wprost wymaga minimum (np. „Jaka jest najmniejsza dopuszczalna kara?” – wtedy zwracasz wartość minimalną).
Jeśli Context zawiera różne liczby, wybierasz tę najbardziej adekwatną do Question.
Jeśli liczba nie jest podana wprost, ale można ją oszacować na podstawie treści (np. „kilka tysięcy” = 2000), zwracasz wartość szacunkową.
Jeśli w Context nie ma liczby, zwracasz „Brak danych”.
Nie podajesz żadnych wyjaśnień, tylko liczbę.

---

Przykłady:

Przykład 1:
Question: Ile osób mieszka w tym mieście?
Context: Populacja miasta wynosi 50 000.
Answer: 50000

Przykład 2:
Question: Jaka jest temperatura wrzenia tej cieczy?
Context: Temperatura wrzenia wynosi 80–100°C.
Answer: 100

Przykład 3:
Question: Jaka jest najmniejsza dopuszczalna kara?
Context: Kara wynosi od 500 do 5000 zł.
Answer: 500

Przykład 4:
Question: Ile lat miał najstarszy uczestnik?
Context: Wiek uczestników wynosił od 25 do 60 lat.
Answer: 60

Przykład 5:
Question: Ile stron ma ta książka?
Context: Brak informacji o liczbie stron.
Answer: Brak danych

---

Question: {question} 
Context: {context}
Answer:
"""

# Load models

In [86]:
try:
    llm = OllamaLLM(model=CFG.model)
    llm_embed = OllamaEmbeddings(model=CFG.model_embed)
except ModuleNotFoundError as e:
    print("Please install ollama first.")
    print(e.msg)
    exit()

# Data preparation

## Load questions

In [ ]:
df_qa = pd.read_csv(CFG.questions_file)
df_qa["question"] = df_qa["question"].str.strip().str.replace(r"\s+", " ", regex=True)

df_qa.head()

,id,question
0,q1,W ciągu ilu dni od przedstawienia projektu procedury zgłoszeń wewnętrznych przez podmiot prawny muszą zakończyć się konsultacje?
1,q2,Od ilu zatrudnionych osób podmiot prawny musi ustanowić wewnętrzną procedurę zgłoszeń naruszeń?
2,q3,W jakim terminie (dni) należy potwierdzić sygnaliście przyjęcie zgłoszenia wewnętrznego?
3,q4,Po ilu miesiącach od upływu terminu kalendarzowego Rzecznik Praw Obywatelskich usuwa dane osobowe związane ze zgłoszeniem zewnętrznym?
4,q5,Przez ile lat podmiot prawny i organ publiczny przechowują dane osobowe związane ze zgłoszeniem?

## Load PDF documents

Documents represent each page in file.

In [88]:
loader = PyPDFLoader(CFG.rag_file)
documents = loader.load()
documents[0]

Document(metadata={'producer': 'Microsoft® Word dla Microsoft 365', 'creator': 'Microsoft® Word dla Microsoft 365', 'creationdate': '2024-06-25T09:38:38+02:00', 'title': 'Ustawa z dnia 14 czerwca 2024 r. o ochronie sygnalistów', 'author': 'RCL', 'moddate': '2024-06-25T09:38:38+02:00', 'source': 'ustawa_o_sygnalistach.pdf', 'total_pages': 17, 'page': 0, 'page_label': '1'}, page_content='©Kancelaria Sejmu    s. 1/17 \n      \n \n2024-06-25 \n \n \nDz. U. 2024 poz. 928 \n \n \nUSTAWA  \nz dnia 14 czerwca 2024 r. \no ochronie sygnalistów1), 2) \nRozdział 1 \nPrzepisy ogólne \nArt. 1. Ustawa reguluje: \n1) warunki objęcia ochroną sygnalistów zgłaszających lub ujawniających publicznie informacje o  naruszeniach prawa; \n2) środki ochrony sygnalistów zgłaszających lub ujawniających publicznie informacje o  naruszeniach prawa; \n3) zasady ustalania wewnętrznej procedury zgłaszania informacji o naruszeniach prawa i podejmowania działań następczych; \n4) zasady zgłaszania informacji o naruszeniach prawa organowi publicznemu; \n5) zasady ujawnienia publicznego informacji o naruszeniach prawa; \n6) zadania Rzecznika Praw Obywatelskich związane ze zgłaszaniem informacji o  naruszeniach prawa; \n7) zadania organów publicznych związane ze zgłaszaniem informacji o naruszeniach prawa i z podejmowaniem działań \nnastępczych. \nArt. 2. Ilekroć w niniejszej ustawie jest mowa o: \n1) działaniu następczym – należy przez to rozumieć działanie podjęte przez podmiot prawny lub organ publiczny w  celu \noceny prawdziwości informacji zawartych w  zgłoszeniu oraz w  celu przeciwdziałania naruszeniu prawa będącemu \nprzedmiotem zgłoszenia, w  szczególności przez postępowanie wyjaśniające, wszczęcie kontroli lub postępowania \nadministracyjnego, wniesienie oskarżenia, działanie podjęte w  celu odzyskania środków finansowych lub zamknięcie \nprocedury realizowanej w  ramach wewnętrznej procedury dokonywania  zgłoszeń naruszeń prawa i  podejmowania \ndziałań następczych lub procedury przyjmowania zgłoszeń zewnętrznych i  podejmowania działań następczych; \n2) działaniu odwetowym – należy przez to rozumieć bezpośrednie lub pośrednie działanie lub zaniechanie w  kontekście \nzwiązanym z pracą, które jest spowodowane zgłoszeniem lub ujawnieniem publicznym i które narusza lub może naru-\nszyć prawa sygnalisty lub wyrz ądza lub może wyrządzić nieuzasadnioną szkodę sygnaliście, w  tym bezpodstawne \ninicjowanie postępowań przeciwko sygnaliście; \n3) informacji o naruszeniu prawa – należy przez to rozumieć informację, w  tym uzasadnione podejrzenie dotyczące za-\nistniałego lub potencjalnego naruszenia prawa, do którego doszło lub prawdopodobnie dojdzie w podmiocie prawnym, \nw którym sygnalista uczestniczył w procesie rekrutacji lub innych negocjacji poprzedzających zawarcie umowy, pracuje \nlub pracował, lub w innym podmiocie prawnym, z którym sygnalista utrzymuje lub utrzymywał kontakt w kontekście \nzwiązanym z pracą, lub informację dotyczącą próby ukrycia takiego naruszenia prawa; \n4) informacji zwrotnej – należy przez to rozumieć przekazaną sygnaliście informację na temat planowanych lub podjętych \ndziałań następczych i powodów takich działań; \n5) kontekście związanym z pracą – należy przez to rozumieć przeszłe, obecne lub przyszłe działania związane z wykony-\nwaniem pracy na podstawie stosunku pracy lub innego stosunku prawnego stanowiącego podstawę świadczenia pracy \nlub usług lub pełnienia funkcj i w podmiocie prawnym lub na rzecz tego podmiotu, lub pełnienia służby w  podmiocie \n \n1) Niniejsza ustawa w zakresie swojej regulacji wdraża dyrektywę Parlamentu Europejskiego i Rady (UE) 2019/1937 z dnia 23 paździer-\nnika 2019  r. w  sprawie ochrony osób zgłaszających naruszenia prawa Unii (Dz.  Urz. UE  L 305 z  26.11.2019, str.  17, Dz.  Urz. \nUE L 347 z 20.10.2020, str. 1, Dz. Urz. UE L 265 z 12.10.2022, str. 1 oraz Dz. Urz. UE L 150 z 09.06.2023, str. 40). \n2) Niniejszą ustawą zmienia się ustawy: ustawę z  dnia 15 lipca 1987 r. o Rzeczniku Praw Obywatelskich oraz ustawę z  dnia 5 sierpnia \n2015 r. o nieodpłatnej pomocy prawnej, nieodpłatnym poradnictwie obywatelskim oraz edukacji prawnej.')

### Split documents into smaller chunks

In [89]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=750, chunk_overlap=125)
all_splits = text_splitter.split_documents(documents)

all_splits[0]

Document(metadata={'producer': 'Microsoft® Word dla Microsoft 365', 'creator': 'Microsoft® Word dla Microsoft 365', 'creationdate': '2024-06-25T09:38:38+02:00', 'title': 'Ustawa z dnia 14 czerwca 2024 r. o ochronie sygnalistów', 'author': 'RCL', 'moddate': '2024-06-25T09:38:38+02:00', 'source': 'ustawa_o_sygnalistach.pdf', 'total_pages': 17, 'page': 0, 'page_label': '1'}, page_content='©Kancelaria Sejmu    s. 1/17 \n      \n \n2024-06-25 \n \n \nDz. U. 2024 poz. 928 \n \n \nUSTAWA  \nz dnia 14 czerwca 2024 r. \no ochronie sygnalistów1), 2) \nRozdział 1 \nPrzepisy ogólne \nArt. 1. Ustawa reguluje: \n1) warunki objęcia ochroną sygnalistów zgłaszających lub ujawniających publicznie informacje o  naruszeniach prawa; \n2) środki ochrony sygnalistów zgłaszających lub ujawniających publicznie informacje o  naruszeniach prawa; \n3) zasady ustalania wewnętrznej procedury zgłaszania informacji o naruszeniach prawa i podejmowania działań następczych; \n4) zasady zgłaszania informacji o naruszeniach prawa organowi publicznemu; \n5) zasady ujawnienia publicznego informacji o naruszeniach prawa;')

# Vector Database

In [90]:
vector_db = InMemoryVectorStore(embedding=llm_embed)
vector_db.add_documents(all_splits)

['08e06f9c-ba23-4815-b990-940a8326d224',
 'e99fcef0-fe72-47eb-863b-f36f3a7c3fde',
 '34342119-8d2f-45a5-8620-b0c233c7251c',
 '07fb29b4-863c-41b9-99d7-2b680571cdc7',
 'db564a80-554c-496c-9d92-947080ff6774',
 '8b86b6d8-d69e-4eb4-b478-40643c16ef23',
 '8fe8e9a3-e77f-4357-b8f0-88edcc956b71',
 '63ccecec-da4d-4cce-b250-1bc8ebd6d4b4',
 'c6dfe8da-7bc6-4b4e-984a-aa271c44fdb8',
 '1c650368-435d-4ff6-a280-57d73c355c98',
 '63a85a3a-0f7f-4335-8f9b-50038b3bb86d',
 'a0f3edb7-c5b8-4ba4-9283-78b36152a76b',
 'c55e771e-8bf3-41ea-b17a-83f2bfaaa769',
 'd9ceb1b3-c221-4ff2-a4ad-88e233bf7e69',
 'eced0e27-5314-4394-9454-5a82dac7f169',
 '682b2e8b-c8c2-458d-9812-9f73fd4e2481',
 'f70b4b3c-3017-4d2e-988d-804192667750',
 'c3c1c717-0b11-4a58-a017-524cd0f46821',
 '70f1905f-97f9-4382-9074-8d87356edbee',
 '486a044a-841f-4f8c-8e88-d02ff84942ee',
 'd1ee966c-dfc7-4e54-bdb7-956f0e215fe4',
 '2f440b6b-d92b-4388-896d-ecf52fcad858',
 'ebfb86ca-384a-4542-ae95-d6378fa4b2b1',
 '7c049b17-569c-46d3-a45d-b1f3b5f47e46',
 '8183b0b8-1ca1-4db6-aa58-89382db76c3d',
 '4174a18c-a61f-49af-81ef-e6ae60a45870',
 'f2b5c229-916d-40bd-9c35-46832ddd1936',
 '4e078e4f-fc19-42f8-8af5-7fb57a65c6e3',
 '53420b26-d9ca-4b28-8a2c-8abea7f182c4',
 '9df9e16e-2283-4a12-8346-eb60ed9b2d21',
 'b3ee02db-9d2c-4f30-8e2f-959405750c97',
 '0c063ac7-a1eb-4af9-90c2-e557601f5064',
 '649cc45b-26e7-4b65-bd16-7d35b5457f81',
 '23959928-3f82-4045-805f-756fb2fef4ec',
 '278363d2-6191-423f-9848-4bdc95e068b5',
 '021efb31-38a5-40e2-9f3e-2581bd68ddd3',
 'f2fd4a98-0da7-4a34-b873-3e28cabb5199',
 '46f1f61a-fe1c-40ad-ad64-376778fb735c',
 '29450c01-6547-4f7d-89e9-0253aef4ec90',
 'a7e6e6ae-d3e4-4e87-ae8c-ba161df83031',
 '7b961c85-009c-4115-a442-bbc712a4cfea',
 'ab11cb6e-6368-482d-894b-bf37cd6db9bb',
 '5767ed49-b88d-44c4-a90b-8983a2a019b4',
 'f4bb13a7-842e-43eb-94a1-e6150fdcbcbc',
 'cfcd849c-3d60-44d0-9246-4a7d6c05ca7f',
 '2d26c86d-a2b6-4689-982b-b3401fd2b901',
 '95a14a57-2181-4b62-bd76-fdd9848cd144',
 'f9732435-4f91-477f-881e-8ae502ace644',
 '72a7623a-7f47-479b-819a-64cd27ce3443',
 'bbdff7ba-8712-4095-b33a-8c03ce6122f7',
 '8640a553-b060-448b-92b0-5e347f4f30e7',
 'eebb5c3b-2d64-409c-91e4-97e14675b12b',
 '54713647-b337-47b6-8062-3d0cc75159f6',
 'c8ef68c7-18d5-49f2-925a-de28f34da62e',
 'f6cd4f9a-cae1-498b-a9c9-79b7544c2623',
 'c3abd2ac-b2c9-4e56-9126-730134d158e3',
 '365304ec-422f-44b4-8eb2-2df59a368b14',
 '296c64d5-b621-40c7-bbd2-9feae065be9c',
 '20f2dede-794d-4c6b-9289-c02ca950e4fe',
 'ae9d203f-8c69-485f-b86d-c702514bc1d1',
 '216da16f-2a21-455b-9397-2d9780237243',
 '0e277ce7-c29b-468e-aa03-f682f95852e8',
 'c11b8b14-5623-4ce4-95db-cc4e2624a989',
 '74b67098-8268-4998-95b3-eb5dcda6e9db',
 'c982d5cf-407f-4f11-a6ce-4934efa4649c',
 '9243ab76-df80-4dac-bb2f-e84b52228b9f',
 '7d54bdec-cda7-4301-a938-86fad2580169',
 '871ab75b-cf15-47a3-8a2d-1cfee57b787c',
 'bf10e808-62b8-47d1-a90c-adc6c33cdda6',
 'a6618572-77ce-4b57-baef-7022b0c64a4e',
 '95f1ab8d-2dfa-4d91-b5e2-ad3c90417ce9',
 'f09f4038-59a6-4e26-a77b-93cd77dbb798',
 '1d10c965-5677-4a80-9213-84c661748a14',
 '020aa2a9-1c69-497c-9820-b90a04ca93e9',
 'e4356752-623b-485c-acae-dd8fc0012b2b',
 '9503802f-6626-47c2-839f-56502dd41954',
 '865a9860-1e6b-421a-8a8f-16a937333dd8',
 '0e261c04-ac82-49f8-839b-2a1e9359e8ec',
 '3d76afb1-ccb6-4e69-ba67-0460984e974a',
 'cfc1afdd-9f0b-4568-8887-b20e1cf4c9cb',
 'd1618858-596b-41a8-9ed9-abaadb7ce599',
 '7e8add7e-2764-4c03-bccd-a3214e093c18',
 '0bde3d78-c701-4125-aa91-b95bb86294a9',
 '77787f4e-6d77-49a4-9a2e-82cc124ae243',
 '96bc5385-863b-4783-9c9b-d6ab3ffe6871',
 '401e6dbc-d71a-41b4-a0ce-4ea168269f0f',
 '67382b42-0e30-4dad-bd87-bf896e65c015',
 'dd31ab55-94b6-4886-8f9e-db0fe5f1e005',
 '8562d71a-fc2d-4837-86d1-fe251af6af5c',
 '2194298a-0a18-4856-99e7-e7be57e26693',
 'a5c16758-f7f4-4cfd-b37b-8d9ea51a4e2b',
 '85ea897c-ae42-4b25-8481-ebcfcf57d4d6',
 'e98338dd-73b5-455f-9bfe-41a3c710fc83',
 '2f1d8738-2686-4388-8823-dab64c85f0a0',
 '7e711c86-7ecd-48a8-a821-50027f33c738',
 'ba64f3c3-c091-43d1-ab7e-ceadf206491f',
 'e111039d-bf41-46a0-8035-831ab86ff8f9',
 '7f5a79be-ba96-479d-a5ed-a71baf5b2409',
 '9cb7a8db-4f71-4793-965b-7af1380a55e0',
 'a4c59a6e-be0c-42b9-9f8e-e262b77b2693',
 '5973c50c-4e5a-4c47-9742-f5fc25d38dd0',
 'da3faf33-5950-4f4b-b0c7-a3d389bd42c1',
 '70155f9b-86e7-4f65-99c1-c2206b29ae63',
 '39745b69-fe60-493e-a6cd-c7d7e6d50328',
 'd232c440-fc6e-4b14-8eba-c572a83b5f86',
 'f464cad8-12dd-4b68-8464-15ce04092871',
 'f75031ca-8497-4148-9ac6-ca218ebf85e3',
 'cb2ddf0f-37f1-4c18-ab64-9dcc5aaf3008',
 '8ab44b3b-9c10-4434-a5ef-38345c42d12c',
 'eebe0f9d-a353-4980-9cfa-19c9103dc7c5',
 '16c5ed85-47f8-4257-8c36-16b4c18fde4a',
 'a3b86f52-feed-49f0-8c55-bcecf0063168',
 '2fa42a05-9205-44ee-a6a4-211f8fa54426',
 '782f68cd-2f6c-4059-a486-d0fed39e91f5',
 'cd121a1e-22ce-4d93-bf09-a22070c18be5',
 'fdec7a34-7e39-494d-9a24-7cd8f8b830fd',
 'dbf8197e-e88f-4c2e-9a6d-a50f5d615aef']

# Prepare prompt

In [91]:
prompt = PromptTemplate(template=AI_PROMPT, input_variables=["context", "question"])

# QA

## Extra functions

In [92]:
def format_docs(docs):
    result = "\n\n".join(doc.page_content for doc in docs)
    return result

In [93]:
def prepare_chain(llm: BaseLanguageModel):
    return (
        {
            "context": vector_db.as_retriever(
                search_kwargs={"score_threshold": 0.9},
            )
            | format_docs,
            "question": RunnablePassthrough(),
        }
        | prompt
        | llm
        | StrOutputParser()
    )

In [94]:
# df_qa["answer"] = df_qa['question'].apply(lambda q: prepare_chain(llm).invoke(q))

In [95]:
# df_qa

In [ ]:
for model in CFG.llm_models:
    llm = OllamaLLM(model=model)
    df_qa[f"answer{model}"] = df_qa["question"].apply(
        lambda q: prepare_chain(llm).invoke(q)
    )

KeyboardInterrupt:

In [ ]:
pd.set_option("display.max_colwidth", None)
df_qa

,id,question,answerqwen2.5:14b,answergemma3:12b,answerSpeakLeash/bielik-11b-v2.3-instruct:Q4_K_M
0,q1,W ciągu ilu dni od przedstawienia projektu procedury zgłoszeń wewnętrznych przez podmiot prawny muszą zakończyć się konsultacje?,10,10,"5. Podmiot prawny ustala procedurę zgłoszeń wewnętrznych po konsultacjach z: \r\n1) zakładową organizacją związkową albo zakładowymi organizacjami związkowymi, jeżeli w podmiocie prawnym działają takie organizacje; \r\n2) przedstawicielami pracowników, wyłonionymi w trybie przyjętym u danego podmiotu prawnego, jeżeli w podmiocie prawnym nie działa zakładowa organizacja związkowa albo zakładowe organizacje związkowe. \r\n\r\nW przypadku braku wyłonienia przedstawicieli pracowników, procedura zgłoszeń wewnętrznych jest ustalana przez podmiot prawny bez konsultacji z przedstawicielami pracowników."
1,q2,Od ilu zatrudnionych osób podmiot prawny musi ustanowić wewnętrzną procedurę zgłoszeń naruszeń?,50,50,"Odpowiedź na pytanie ""Ile osób musi być zatrudnionych w podmiocie prawnym, aby był on zobowiązany do ustanowienia procedury zgłoszeń wewnętrznych?"":\r\n\r\nZgodnie z treścią tekstu, podmiot prawny jest zobowiązany do ustanowienia procedury zgłoszeń wewnętrznych, jeśli zatrudnia co najmniej 50 osób. Wynika to z faktu, że wymóg ten dotyczy podmiotów prawnych, które zatrudniają odpowiednią liczbę pracowników (w tym przypadku co najmniej 50).\r\n\r\nWarto również zauważyć, że procedura zgłoszeń wewnętrznych powinna być ustalona po konsultacjach z odpowiednimi podmiotami, takimi jak zakładowa organizacja związkowa lub przedstawiciele osób świadczących pracę na rzecz podmiotu prawnego. Konsultacje te powinny trwać nie krócej niż 5 dni i nie dłużej niż 10 dni od dnia przedstawienia projektu procedury zgłoszeń wewnętrznych."
2,q3,W jakim terminie (dni) należy potwierdzić sygnaliście przyjęcie zgłoszenia wewnętrznego?,"Na podstawie przeczytanych przepisów prawnych, termin na przekazanie zgłoszenia zewnętrznego przez Rzecznika Praw Obywatelskich do właściwego organu publicznego wynosi **14 dni** od dnia dokonania zgłoszenia. Zatem odpowiedź to **14 dni**.",14,"W odpowiedzi na pytanie dotyczące przepisów ustawy o ochronie osób zgłaszających naruszenia prawa, chciałbym wyjaśnić kilka kluczowych kwestii: \r\n\r\n1. **Wstępna weryfikacja zgłoszenia zewnętrznego przez Rzecznika Praw Obywatelskich**: Zgodnie z art. 32 ustawy, Rzecznik Praw Obywatelskich przeprowadza wstępną weryfikację zgłoszenia zewnętrznego, aby ustalić, czy dotyczy ono informacji o naruszeniu prawa oraz zidentyfikować organ publiczny właściwy do podjęcia działań następczych. Jeśli zgłoszenie dotyczy naruszenia prawa, Rzecznik Praw Obywatelskich przekazuje je niezwłocznie, ale nie później niż w terminie 14 dni od dnia dokonania zgłoszenia, do odpowiedniego organu publicznego. Jeśli zgłoszenie nie dotyczy naruszenia prawa, Rzecznik Praw Obywatelskich informuje o tym sygnalistę i może wskazać inne tryby rozpatrzenia sprawy.\r\n\r\n2. **Przekazanie zgłoszenia zewnętrznego do organu publicznego**: Rzecznik Praw Obywatelskich przekazuje zgłoszenie zewnętrzne do właściwego organu publicznego, który jest odpowiedzialny za podjęcie działań następczych. Organ ten powinien niezwłocznie podjąć czynności mające na celu zbadanie sprawy i ustalenie, czy doszło do naruszenia prawa. Jeśli organ publiczny nie podejmie żadnych działań następczych ani nie przekaże sygnaliście informacji zwrotnej w określonym terminie, sygnalista może dokonać zgłoszenia zewnętrznego bezpośrednio do organu publicznego.\r\n\r\n3. **Odstąpienie od przekazania zgłoszenia**: Rzecznik Praw Obywatelskich może odstąpić od przekazania zgłoszenia zewnętrznego, jeśli ustali, że informacja objęta zgłoszeniem podlega rozpatrzeniu w trybie przewidzianym w innych przepisach, takich jak powództwo cywilne, zawiadomienie o podejrzeniu popełnienia przestępstwa, skarga do sądu administracyjnego, skarga, wniosek lub petycja. W takim przypadku Rzecznik Praw Obywatelskich informuje sygnalistę o możliwościach dalszego postępowania.\r\n\r\n4. **Zasady dotyczące zgłoszeń zewnętrznych**: Zgodnie z ustawą, sygnalista ma prawo dokonać zgłoszenia zewnętrznego bezpośrednio do organu publicznego, jeśli Rzecznik Praw Obywatelskich nie przekazał zgłoszenia w terminie lub odstąpił od jego przekazania. Sygnalista może również dokonać zgłoszenia zewnętrznego bezpośrednio do organu publicznego, jeśli organ ten nie podjął żadnych działań następczych ani nie przekazał informacji zwrotnej w określonym terminie. W takich sytuacjach sygnalista ma prawo do ochrony przed represjami i dyskryminacją związaną ze zgłoszeniem naruszenia prawa.\r\n\r\nPodsumowując, ustawa o ochronie osób zgłaszających naruszenia prawa określa procedury wstępnej weryfikacji zgłoszeń zewnętrznych przez Rzecznika Praw Obywatelskich oraz przekazywania ich do odpowiednich organów publicznych. Ustawa gwarantuje również sygnalistom prawo do dokonania zgłoszenia zewnętrznego bezpośrednio do organu publicznego w określonych sytuacjach oraz ochronę przed represjami i dyskryminacją."
3,q4,Po ilu miesiącach od upływu terminu kalendarzowego Rzecznik Praw Obywatelskich usuwa dane osobowe związane ze zgłoszeniem zewnętrznym?,Brak danych,14,"Na podstawie podanego tekstu, nie można jednoznacznie określić terminu, po którym dane osobowe sygnalisty są usuwane. Tekst zawiera informacje o przetwarzaniu i ochronie danych osobowych w kontekście zgłoszeń dotyczących naruszeń prawa, ale nie precyzuje dokładnego terminu usunięcia tych danych. Wskazuje jedynie, że ""dane osobowe, które nie mają znaczenia dla rozpatrywania zgłoszenia, są niezwłocznie usuwane"", a w przypadku przypadkowego zebrania takich danych - ""usunięcie tych danych osobowych następuje w terminie 14 dni od chwili ustalenia, że nie mają one znaczenia dla sprawy"". Nie ma informacji o usuwaniu danych po określonym czasie od momentu zgłoszenia."
4,q5,Przez ile lat podmiot prawny i organ publiczny przechowują dane osobowe związane ze zgłoszeniem?,3,12,"3 lat po zakończeniu roku kalendarzowego, w którym przekazano zgłoszenie zewnętrzne do organu publicznego właściwego do podjęcia działań następczych."
5,q6,W ciągu ilu dni od otrzymania wniosku musi zostać zorganizowane bezpośrednie spotkanie w przypadku zgłoszenia ustnego?,Brak danych,Brak danych,"Brak konkretnej informacji w podanym tekście dotyczącej terminu na zorganizowanie spotkania po otrzymaniu zgłoszenia. Tekst zawiera przepisy prawne i procedury dotyczące zgłaszania naruszeń prawa, ale nie określa bezpośrednio czasu, w jakim należy zorganizować spotkanie po otrzymaniu takiego zgłoszenia."
6,q7,Ile dni ma organ publiczny na przekazanie zgłoszenia zewnętrznego do właściwego organu?,Brak danych,Brak danych,"Brak konkretnego terminu w podanym fragmencie tekstu. Aby odpowiedzieć na to pytanie, potrzebne są dodatkowe informacje lub pełny tekst ustawy. W oparciu o dostępny fragment, nie można jednoznacznie określić terminu na przekazanie informacji zwrotnej przez organ publiczny."
7,q8,"Ile osób minimum musi mieszkać w gminie lub powiecie, aby jednostki organizacyjne musiały stosować przepisy o zgłoszeniach wewnętrznych?",10000,50,"5. Art. 23 ust. 5 stanowi, że przepisów rozdziału 6 nie stosuje się do jednostek organizacyjnych gminy lub powiatu liczących mniej niż 10 000 mieszkańców. Oznacza to, że w takich jednostkach organizacyjnych nie ma obowiązku ustalania procedury zgłoszeń wewnętrznych ani podejmowania działań następczych w przypadku otrzymania zgłoszenia naruszenia prawa. Jednakże, jeśli taka jednostka organizacyjna chce ustalić procedurę zgłoszeń wewnętrznych lub podejmować działania następcze, może to zrobić na zasadzie dobrowolności. W takim przypadku, jednostka organizacyjna powinna ustalić procedurę zgłoszeń wewnętrznych zgodną z wymogami określonymi w rozdziale 6 ustawy o ochronie osób zgłaszających naruszenia prawa."
8,q9,Co ile lat minimum Rzecznik Praw Obywatelskich i organ publiczny muszą dokonywać przeglądu procedury zgłoszeń?,Brak danych,7,"Brak informacji o okresie, po którym Rzecznik Praw Obywatelskich i organ publiczny powinni dokonać przeglądu procedury zgłoszeń zewnętrznych. W tekście nie ma wzmianki o regularnym przeglądzie tej procedury przez Rzecznika Praw Obywatelskich i organ publiczny. Zatem, na podstawie dostępnych informacji, nie można określić, co ile lat powinien być dokonywany przegląd tej procedury."
9,q10,Ile lat pozbawienia wolności grozi za ujawnienie tożsamości sygnalisty?,"Podany tekst prawa nie zawiera informacji na temat kary za działania odwetowe lub konkretnej kary za ujawnianie informacji o naruszeniach (np. zgłaszanie przestępstw). Z tego co wynika z tekstu, chodzi głównie o zakaz działań odwetowych i ochronę sygnalistów przed takimi działaniami.\n\nJednak w praktyce kary za działania odwetowe (np. za próbę utrudnienia czy skuteczne utrudnienie znalezienia pracy po zgłoszeniu) są przewidziane w innych artykułach ustawy oDisclosure of Information on Violations (Informacja na temat tego rodzaju ustawy jest nieaktualna, więc dokładny odniesienie powinno być sprawdzone w bieżącym kodeksie karnym danego kraju). \n\nAby odpowiedzieć konkretniej na Twoje pytanie o karę za zgłoszenie informacji o przestępstwach, zwykle to prawa są chronione i nie ma specyficznej kary dla sygnalistów. Jeśli chodzi o konkretne kary za ukrywanie lub utrudnianie dochodzenia w sprawie przestępstwa, one są podane w kodeksie karnym danego kraju.\n\nW ramach kodeksu karnego kara może być na przykład wykończeniem pracowitym, aresztem lub karą gminną. W niektórych przypadkach也可能涉及罚款或其他形式的处罚。然而，您提供的法律文本中并没有具体提及举报行为本身的惩罚措施。通常，在大多数司法管辖区，举报违法行为（如揭发犯罪）的人受到保护，不会因为正当的举报行为而被处以刑罚。\n\n如果您想了解具体的刑事处罚措施，请参考相关国家或地区的刑法典中的特定条款，比如关于妨碍司法公正、泄露机密信息或者进行报复性行动的具体惩罚规定。这些通常会在刑法的相关章节中详细列出。\n\n请提供更具体的问题背景或法律条文编号，以便我可以给出更加准确的答案。",Brak danych.,"Wygląda na to, że masz pytania dotyczące projektu ustawy o ochronie osób zgłaszających naruszenia prawa (sygnalistów) w Polsce. Oto odpowiedzi na niektóre z Twoich pytań:\n\n1. **Czy pracodawca może zwolnić sygnalistę?**\n - Tak, ale tylko pod warunkiem, że istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one związane bezpośrednio lub pośrednio ze zgłoszeniem naruszenia.\n\n2. **Czy pracodawca może zmienić warunki pracy sygnalisty?**\n - Tak, ale podobnie jak w przypadku zwolnienia, muszą istnieć ważne przyczyny niedotyczące osoby sygnalisty i nie mogą one być bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n3. **Czy pracodawca może odmówić awansu sygnaliście?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one związane bezpośrednio lub pośrednio ze zgłoszeniem naruszenia.\n\n4. **Czy pracodawca może zmniejszyć wynagrodzenie sygnaliście?**\n - Tak, ale podobnie jak w przypadku innych działań, muszą istnieć ważne przyczyny niedotyczące osoby sygnalisty i nie mogą one być bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n5. **Czy pracodawca może przenieść sygnalistę na inne stanowisko?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n6. **Czy pracodawca może wstrzymać udział sygnalisty w szkoleniach podnoszących kwalifikacje zawodowe?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n7. **Czy pracodawca może skierować sygnalistę na badania lekarskie, w tym psychiatryczne?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n8. **Czy pracodawca może podjąć działania mające na celu utrudnienie znalezienia pracy w przyszłości?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n9. **Czy pracodawca może wyrządzić szkodę finansową sygnaliście?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\n10. **Czy pracodawca może wyrządzić inną szkodę sygnaliście, np. naruszenie dóbr osobistych?**\n - Tak, ale tylko wtedy, gdy istnieją ważne przyczyny niedotyczące osoby sygnalisty i nie są one bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia.\n\nWarto pamiętać, że wszystkie te działania muszą być uzasadnione ważnymi przyczynami niedotyczącymi osoby sygnalisty i nie mogą być bezpośrednio lub pośrednio związane ze zgłoszeniem naruszenia. W przeciwnym razie, takie działania mogą być uznane za przejaw mobbingu lub dyskryminacji i będą podlegać odpowiedzialności prawnej."